config/routes.rb
# require "sidekiq/web"

Rails.application.routes.draw do

  # if Rails.env.production?
  #   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  #     ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
  #     ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  #   end
  # end

  # mount Sidekiq::Web => "/sidekiq"
  mount ForestLiana::Engine => "/forest"
  root "pages#homepage"

  get "/robots.:format" => "pages#robots"
  get "about", to: "pages#about"
  # get "blog", to: "pages#blog"
  get "faq", to: "pages#faq"
  get "terms", to: "pages#terms"
  get "privacy", to: "pages#privacy"
  get "dmca", to: "pages#dmca"

  resources "contact_forms", only: [:new, :create], path: "contact", path_names: { new: "" }

  devise_for  :members,
              path: "",
              path_names: {sign_up: "signup", sign_in: "login", sign_out: "logout", edit: "profile"},
              controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions" }

  # memberships
  mount Payola::Engine => "/payola", as: :payola
  get "membership/new", to: "memberships#new", as: :new_membership
  get "membership/new/special", to: "memberships#new_special", as: :new_membership_special
  get "membership", to: "memberships#subscriptions", as: :subscriptions
  get "thanks", to: "memberships#thanks", as: :thanks
  # resources :memberships, except: [:new]

  # resources :subscriptions

  # videos
  get "videos/search", to: "videos#search", as: :videos_search
  get "videos/videos", to: "videos#video", as: :video
  get "videos/convert", to: "videos#convert", as: :convert_video
  get "videos/download_history", to: "videos#download_history", as: :download_history
  get "videos/download", to: "videos#download", as: :download_video
  get "videos/delay_download", to: "videos#delay_download", as: :delay_download
  get "videos/:title", to: "videos#video", as: :video_title
  get "videos/:converted_video_id/dispatch_download_file", to: "videos#dispatch_download_file", as: :dispatch_download_file

end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  # validates :title, :ytid, :duration, :video_file, :format, presence: true

  attr_accessor :actual_end_time

  has_many :converted_videos
  has_one  :tinyproxy_ip

  mount_uploader :video_file, VideoUploader

  extend FriendlyId
  friendly_id :title, use: :slugged, slug_column: :url_title

  scope :with_information, -> { where.not(url_title: nil) }

  ALLOWEDFORMATS = [
    ['Video',
     [
       %w[MP4 mp4],
       # ["3GP", "3gp"],
       %w[AVI avi],
       %w[FLV flv],
       %w[MKV mkv],
       # ["OGG", "ogg"],
       %w[WEBM webm]
     ]],
    ['Audio',
     [
       %w[MP3 mp3],
       %w[AAC aac],
       %w[M4A m4a],
       %w[WAV wav]
     ]]
  ].freeze

  def filename
    "#{title}.#{format}"
  end

  def check_incomplete_master_video
    title.blank? || video_file.file.blank?
  end

  def video_file_path
    video_file.url
  end

  def fetch_proxy
    Tinyproxy.new.get_proxy(true)
  end

  class << self
    def build_options
      request_options = {}

      youtube_options = {
        config_location: 'config/youtube-dl.conf',
        ffmpeg_location: FFMPEG.ffmpeg_binary
      }

      if Rails.application.credentials[Rails.env.to_sym][:TINYPROXY_ENABLED] == 'true'
        proxy = Tinyproxy.new.get_proxy(false, 'one', true)
        youtube_options.merge!(proxy: proxy['proxy']) unless proxy['proxy'].blank?
      else
        proxy = {
          'proxy' => '',
          'ip' => ''
        }
      end

      request_options.merge!(youtube_options: youtube_options, proxy: proxy)
    end

    def remove_leading_zero_hours(length)
      hours, minutes, seconds = length.split(':')
      if hours == '00'
        start_time = '00:00'
        end_time = "#{minutes}:#{seconds}"
      else
        start_time = '00:00:00'
        end_time = length
      end
      [start_time, end_time]
    end

    def format_url(search_url)
      if ['http://m.youtu', 'https://m.youtu'].any? { |url| search_url.include? url }
        search_url = search_url.gsub('m.youtube', 'www.youtube')
      end
      search_url
    end
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

require 'will_paginate/array'
class VideosController < ApplicationController
  include Evercookie::ControllerHelpers

  before_action :authenticate_member!, only: [:download_history]
  before_action :load_converted_video, :set_evercookie_value, only: %i[download dispatch_download_file]
  before_action :remove_blocked_videos, only: :video

  def search
    if search_params[:terms].present?
      if ['http://youtu', 'http://www.youtu', 'https://youtu', 'https://www.youtu', 'http://m.youtu', 'https://m.youtu'].any? { |url| search_params[:terms].include? url }

        # fetch info from video URL
        video = Yt::URL.new(Video.format_url(search_params[:terms]))
        if video.kind.to_s == 'video'
          redirect_to action: 'video', id: video.id
        else
          flash[:error] = 'Error: Video not found. Check the URL you entered.'
          redirect_back(fallback_location: (request.referer || root_path))
        end
      else
        videos = Youtube::VideosCollection.new(search_params[:terms]).search_by_terms
        if videos.is_a?(Yt::Collections::Videos)
          @videos = videos.send(:list).to_a.paginate(page: params[:page], per_page: 12)
        else
          flash[:error] = 'Error: Sorry, no videos found.'
          redirect_back(fallback_location: (request.referer || root_path))
        end
      end
    else
      flash[:error] = 'Error: Please enter a search term.'
      redirect_back(fallback_location: (request.referer || root_path))
    end
  end

  def video
    if params[:id].present?
      # fetch info from video ID
      video = Video.with_information.find_by_ytid(params[:id])
      video ||= Yt::Video.new(id: params[:id])
    elsif params[:title].present?
      max_results = 1
      video = Video.find_by_url_title(params[:title])
      # Fetching video from youtube by performing search using the title present in the pretty url
      unless video
        found = Youtube::VideosCollection.new(params[:title], max_results).fetch_videos_by_title.first
        video = Video.with_information.find_by_ytid(found.id) if found
        video ||= found
      end
    end
    if video.blank?
      flash[:error] = 'Error: Video not found. Check the search terms you entered.'
      redirect_back(fallback_location: (request.referer || root_path))
    else
      @video = YtVideo.new(video)
      begin
        if @video.live?
          flash[:error] = 'Error: Live videos not supported'
          redirect_back(fallback_location: (request.referer || root_path))
        else
          if @video.lengthy_video?
            flash[:error] = 'Sorry, video too long. Please try another video.'
            redirect_back(fallback_location: (request.referer || root_path))
          else
            session['after_sign_up_redirect_path'] = request.original_url
            session['after_sign_in_redirect_path'] = request.original_url
            @start_time, @end_time = Video.remove_leading_zero_hours(@video.humanize_duration)
            @has_active_subscription = current_member.blank? ? false : current_member.subscriptions.active.any?
            load_gon_variables
          end
        end
      # This is to handle OpenTimeout error, this error is raised if a connection cannot be created within the open_timeout.
      rescue Net::OpenTimeout
        flash[:error] = 'Error: Network connection!'
        redirect_back(fallback_location: (request.referer || root_path))
      rescue Yt::NoItemsError
        flash[:error] = 'Error: Video not found. Check the search terms you entered.'
        redirect_back(fallback_location: (request.referer || root_path))
      end
    end
  end

  def convert
    redirect_back(fallback_location: (request.referer || root_path)) unless request.xhr?
    # evercookie_is_set? method is used to check whether evercookie is set or not
    if policy(Video).authorized_to_download?(evercookie_is_set?(:guest_uid))
      options = {
        id: params[:id],
        session_identifier: video_session_identifier,
        video_format: params[:video_format],
        start_time: params[:start_time],
        end_time: params[:end_time],
        actual_end_time: params[:actual_end_time],
        retries: 0
      }
      @video = Video.find_or_create_by!(ytid: params[:id])
      conversion_delay = Rails.application.credentials[Rails.env.to_sym][:VIDEO_WAIT_START_CONVERSION_SECONDS].to_i
      if ConvertedVideo.validate_start_end_time(params[:start_time], params[:end_time])
        VideoConversionJob.set(wait: conversion_delay).perform_later(options, @video)
      else
        @message = 'Error: Please check start time and end time values!'
      end
    else
      download_limit = Rails.application.credentials[Rails.env.to_sym][:GUEST_VIDEO_CONVERSION_LIMIT]
      @message = "Download limit of #{download_limit} videos reached. Join as member for unlimited downloads!"
    end
  end

  def download
    redirect_back(fallback_location: (request.referer || root_path)) unless request.xhr?

    if policy(@converted_video).allow_download?
      if @converted_video.video_file.file.exists?
        respond_to do |format|
          @url = "/videos/#{params[:converted_video_id]}/dispatch_download_file"
          format.js { render partial: 'download_file' }
        end
      else
        @message = 'Error: file missing.'
      end
    end
  end

  def dispatch_download_file
    @file = @converted_video.initiate_download(current_member, @converted_video, ApplicationHelper.remote_ip_address, evercookie_get_value(:guest_uid))
    send_file(
      @file,
      filename: @converted_video.filename,
      type: @converted_video.video_file.content_type,
      disposition: 'attachment'
    )
  end

  def download_history
    @download_history = ConvertedVideo.joins(:member_downloads).where('member_downloads.member_id = ?', current_member.id).paginate(page: params[:page], per_page: 8).order('created_at DESC')
  end

  def delay_download
    # evercookie_is_set? method is used to check whether evercookie is set or not
    display_guest_delay = policy(Video).show_guest_delay?(evercookie_is_set?(:guest_uid))
    data = { status: display_guest_delay, delay_seconds: Rails.application.credentials[Rails.env.to_sym][:GUEST_DELAY_COUNTDOWN_SECONDS].to_i }.to_json
    respond_to do |format|
      format.json { render json: data }
    end
  end

  private

  def search_params
    params.permit(
      :terms
    )
  end

  def load_converted_video
    @converted_video = ConvertedVideo.find_by_id(params[:converted_video_id])
  end

  # set evercookie
  def set_evercookie_value
    set_evercookie(:guest_uid, Digest::SHA1.hexdigest([Time.now, rand].join))
  end

  def load_gon_variables
    gon.video_start_time = @start_time
    gon.video_end_time = @end_time
    gon.guest_video_duration_limit_minutes = Rails.application.credentials[Rails.env.to_sym][:GUEST_VIDEO_DURATION_LIMIT_MINUTES].to_i
    gon.has_active_subscription = @has_active_subscription
    gon.video_converting_modal_showafter_seconds = Rails.application.credentials[Rails.env.to_sym][:VIDEO_CONVERTING_MODAL_SHOWAFTER_SECONDS].to_i
    gon.host_url = Rails.application.credentials[Rails.env.to_sym][:WEB_HOST] || 'http://localhost:3000'
  end

  def remove_blocked_videos
    blocked_videos = %w[calvin-harris-sam-smith-promises-official-lyric-video dTQMd2I3drE]
    blocked_videos.each do |title|
      if (params[:title].present? && params[:title].include?(title)) || (params[:id].present? && params[:id].include?(title))
        flash[:error] = 'Error: Video not found.'
        redirect_back(fallback_location: (request.referer || root_path))
      end
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper

  def seconds_to_time_helper(seconds)
    if seconds < 3600
      format = '%M:%S'
    else
      format = '%H:%M:%S'
    end
    Time.at(seconds).utc.strftime(format)
  end

  def number_with_delimiter_helper(number)
    number_with_delimiter(number.to_s, delimiter: ",")
  end

  def published_at_helper(date)
    return nil if date.blank?
    date.strftime("%b %d, %Y")
  end

  def download_at_helper(datetime)
    datetime.strftime("%m/%d/%Y")
  end

  def serial_number_helper(page, per_page, row)
    count = ((page || 1).to_i - 1) * per_page
    count + row + 1
  end

end

app/views/videos/_4_cards_row.html.slim
- @videos_collection.each do |video|
  .col-6.col-md-3
    .card.mb-3
      = link_to video_path(id: video.ytid) do
        = image_tag(video.thumbnail_url(:medium), alt: "#{video.title}", class: "card-img-top img-fluid")
        .card-img-overlay.duration-position
          small.float-right
            strong.bg-dark.text-white
              | &nbsp;
              = seconds_to_time_helper(video.duration)
              | &nbsp;
      .card-body.custom-padding
        .card-subtitle.clearfix
          small.float-left
            = published_at_helper(video.published_on)
          small.float-right
            = number_with_delimiter_helper(video.views) + "  views"
        h6.card-title.custom-padding
          small
            = link_to "#{truncate(video.title, length: 105)}".html_safe, video_path(id: video.ytid), "data-turbolinks": false
        / p.card-text
        /   small
        /     = truncate(video.description, length: 200)

app/views/videos/_breadcrumbs.html.slim
nav.breadcrumb
  = link_to "Home", root_path, class: "breadcrumb-item"
  - if controller_name == "videos" && action_name == "search"
    span.breadcrumb-item.active Search results
  - if controller_name == "videos" && action_name == "video"
    = link_to "Search results", request.referrer.present? ? request.referrer : root_path, class: "breadcrumb-item"
    span.breadcrumb-item.active 
      = truncate(@video.title, length: 100)

app/views/videos/_convert_options.html.slim
= form_tag(convert_video_path, method: "get", remote: true) do
  = hidden_field_tag "id", @video.ytid
  = hidden_field_tag "identifier", video_session_identifier
  = hidden_field_tag "actual_end_time", @end_time
  .row.form-group
    .col-3
      label.col-form-label for="video-format" Format
    .col-5
      = select_tag "video_format", grouped_options_for_select(Video::ALLOWEDFORMATS), id: "video-format", class: "form-control"
  / .row.form-group
  /   .col-3
  /     label.col-form-label for="quality" Quality
  /   .col-6
  /     select#quality.form-control
  /       option 1080p HD
  /       option 720p HD
  /       option 480p
  /       option 360p
  /       option 240p
  .row.form-group
    .col-4
      label.col-form-label for="start-time" Start
      button.btn.cursor-pointer#reset-start-time data-placement="top" data-toggle="tooltip" title=("Reset") type="button"
        | <i class="fa fa-undo"></i>
      = text_field_tag "start_time", @start_time, id: "start-time", class: "form-control text-center"
    .col-4
      label.col-form-label for="end-time" End
      button.btn.cursor-pointer#reset-end-time data-placement="top" data-toggle="tooltip" title=("Reset") type="button"
        | <i class="fa fa-undo"></i>
      = text_field_tag "end_time", @end_time, id: "end-time", class: "form-control text-center"
  / .row.form-group
  /   .col-12.form-check
  /       label.form-chck-label         input#agree-tos.form-check-input type="radio"
  /         |    I agree to the
  /         a href="#" Terms of Service
  .row#start-conversion
    .col-12
      button.btn.btn-lg.btn-block.btn-success#conversion-start-button type="submit"
        | <i class="fa fa-play-circle"></i>&nbsp;&nbsp;Start conversion
  br
  .row#conversion-card
    .col-12
      .card.bg-light
        .card-body
          h5.card-title.text-center
            | <i id="conversion-timer-spinner" class="fa fa-refresh fa-spin fa-lg fa-fw"></i>&nbsp;
            | Conversion time:
            strong.text-danger.conversion-timer
              | &nbsp;0 seconds
          .row#conversion-progress-status
            .col-12
              | Status:&nbsp;
              span#conversion-status-text data-id = @video.ytid
                | Starting...
          .row#conversion-progress-bar
            .col-12
              .progress[style="height: 1.5rem"]
                .progress-bar.bg-warning.progress-bar-striped.progress-bar-animated aria-valuemax="100" aria-valuemin="0" aria-valuenow="5" role="progressbar" style="width: 5%" 5%
          br
          .row#download-file
            .col-12
              = link_to "<i class='fa fa-cloud-download'></i>&nbsp;&nbsp;Download file".html_safe, "javascript:void(0)", id: "download-file-button", class: "btn btn-lg btn-block btn-primary disabled", "data-turbolinks": false, remote: true
  br
  .row#guest-delay
    .col-12
      .card.bg-light
        .card-body
          h5.card-title.text-center.guest-delay-countdown
            | <i id="delay-timer-spinner" class="fa fa-refresh fa-spin fa-lg fa-fw"></i>&nbsp;
            | Please wait:
            strong.text-danger.delay-timer
              | &nbsp;30 seconds
          .row.guest-delay-countdown
            .col-5
              hr
            .col-2
             | or
            .col-5
              hr
          h5.card-title.text-center
            | Create a membership to get:
          .card-text
            .row.justify-content-center
              .col-9
                p
                  i.fa.fa-check.text-success
                  | &nbsp;&nbsp;&nbsp;Skip download delay
                  br
                  i.fa.fa-check.text-success
                  | &nbsp;&nbsp;&nbsp;Unlimited number of downloads
                  br
                  i.fa.fa-check.text-success
                  | &nbsp;&nbsp;&nbsp;Unlimited duration videos
                  / br
                  / i.fa.fa-check.text-success
                  / | &nbsp;&nbsp;&nbsp;Tech support for help
          = link_to "Start free trial&nbsp;&nbsp;<i class='fa fa-arrow-circle-right'></i>".html_safe, new_membership_path, class:"button btn btn-lg btn-block btn-warning"
          / = link_to "Start 1 day free trial&nbsp;&nbsp;<i class='fa fa-arrow-circle-right'></i>".html_safe, new_membership_path, class:"button btn btn-lg btn-block btn-yellow"

app/views/videos/_download_file.js.erb
window.location.href = "<%= @url %>"

app/views/videos/convert.js.erb
<% unless @message.blank? %>
  $(".justify-content-end").html("<%= j render partial: 'layouts/flash_message', locals: {message_type: 'error', message: @message} %>");
  guest_download_limit_triggered();
<% end %>
<% unless @video.blank? %>
  $("#conversion-status-text").attr("data-id", "<%= @video.id %>");
<% end %>

app/views/videos/download.js.erb
<% unless @message.blank? %>
  $(".justify-content-end").html("<%= j render partial: 'layouts/flash_message', locals: {message_type: 'error', message: @message} %>");
<% end %>
<% unless policy(@converted_video).allow_download? %>
  $('#signupModalCenter').modal('show');
<% end %>

app/views/videos/download_history.html.slim
- title 'Download history'

.container
  .row.justify-content-center.my-4
    .col-lg-6
      h4 Download history
      table.table.table-responsive.table-striped.table-hover
        thead.thead-dark
          tr
            th #
            th Date
            th Video
            th Format
            / th Status
            th
        tbody
          - @download_history.each_with_index do |converted_video, index|
            - video = converted_video.video
            tr
              td
                = serial_number_helper(params[:page], @download_history.per_page, index)
              td
                = download_at_helper(converted_video.created_at)
              td
                = link_to video.title, video_path(id: video.ytid)
              td
                = converted_video.format.upcase
              / td
              /   h1.badge.badge-warning In process
              td
                = link_to 'Download', download_video_path(converted_video_id: converted_video.id), class: "button btn btn-sm btn-outline-primary", "data-turbolinks": false, remote: true
  .row.justify-content-center
    = will_paginate @download_history

app/views/videos/search.html.slim
- title 'Search for ' + params[:terms]
- meta_tag :keywords, params[:terms]

.container
  = render "videos/breadcrumbs"
  .row
    - @videos.each do |video|
      .col-6.col-md-3
        .card.mb-3
          = link_to video_path(id: video.id) do
            = image_tag(video.thumbnail_url(:medium), alt: "#{video.title}", class: "card-img-top img-fluid")
            .card-img-overlay.duration-position
              small.float-right
                strong.bg-dark.text-white
                  | &nbsp;
                  = seconds_to_time_helper(video.duration)
                  | &nbsp;
          .card-body.custom-padding
            .card-subtitle.clearfix
              small.float-left
                = published_at_helper(video.published_at)
              small.float-right
                = number_with_delimiter_helper(video.view_count) + "  views"
            h6.card-title.custom-padding
              small
                = link_to "#{truncate(video.title, length: 105)}".html_safe, video_path(id: video.id), "data-turbolinks": false
            / p.card-text
            /   small
            /     = truncate(video.description, length: 200)
  .row.justify-content-center
    = will_paginate @videos

app/views/videos/video.html.slim
- title @video.title
- meta_tag :description, @video.description
- meta_tag :keywords, @video.keywords
- check_evercookie(:uid)

div.container.video-display data-id="#{@video.title.parameterize}"
  = render "videos/breadcrumbs"
  .row.my-2
    .col-md-7
      .embed-responsive.embed-responsive-16by9
        iframe.embed-responsive-item allowfullscreen="" src="https://www.youtube.com/embed/#{@video.ytid}"
      br
      p.float-right
        = number_with_delimiter(@video.views.to_s, delimiter: ",") + "  views"
      p
        = "Published on " + @video.published_on.strftime("%B %d, %Y")
      h5
        = truncate(@video.title, length: 100)
      p.d-none.d-sm-inline
        = truncate(@video.description, length: 600)
      .d-inline.d-sm-none
        hr
    .col-md-5
      =render "videos/convert_options"