config/routes.rb
# require "sidekiq/web"

Rails.application.routes.draw do

  # if Rails.env.production?
  #   Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  #     ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
  #     ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  #   end
  # end

  # mount Sidekiq::Web => "/sidekiq"
  mount ForestLiana::Engine => "/forest"
  root "pages#homepage"

  get "/robots.:format" => "pages#robots"
  get "about", to: "pages#about"
  # get "blog", to: "pages#blog"
  get "faq", to: "pages#faq"
  get "terms", to: "pages#terms"
  get "privacy", to: "pages#privacy"
  get "dmca", to: "pages#dmca"

  resources "contact_forms", only: [:new, :create], path: "contact", path_names: { new: "" }

  devise_for  :members,
              path: "",
              path_names: {sign_up: "signup", sign_in: "login", sign_out: "logout", edit: "profile"},
              controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations", sessions: "sessions" }

  # memberships
  mount Payola::Engine => "/payola", as: :payola
  get "membership/new", to: "memberships#new", as: :new_membership
  get "membership/new/special", to: "memberships#new_special", as: :new_membership_special
  get "membership", to: "memberships#subscriptions", as: :subscriptions
  get "thanks", to: "memberships#thanks", as: :thanks
  # resources :memberships, except: [:new]

  # resources :subscriptions

  # videos
  get "videos/search", to: "videos#search", as: :videos_search
  get "videos/videos", to: "videos#video", as: :video
  get "videos/convert", to: "videos#convert", as: :convert_video
  get "videos/download_history", to: "videos#download_history", as: :download_history
  get "videos/download", to: "videos#download", as: :download_video
  get "videos/delay_download", to: "videos#delay_download", as: :delay_download
  get "videos/:title", to: "videos#video", as: :video_title
  get "videos/:converted_video_id/dispatch_download_file", to: "videos#dispatch_download_file", as: :dispatch_download_file

end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" type="image/png" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="apple-touch-icon" type="image/png" href="<%= asset_path 'favicon/apple-touch-icon-precomposed.png' %>">

<link rel="apple-touch-icon" type="image/png" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="167x167" href="<%= asset_path 'favicon/apple-touch-icon-167x167.png' %>">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon-180x180.png' %>">

<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="shortcut icon" type="image/ico" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="shortcut icon" type="image/x-icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<%= asset_path 'favicon/favicon.ico' %>">

<link rel="icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="icon" type="image/ico" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="icon" type="image/x-icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<link rel="icon" type="image/vnd.microsoft.icon" href="<%= asset_path 'favicon/favicon.ico' %>">

<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="194x194" href="<%= asset_path 'favicon/favicon-194x194.png' %>">
<link rel="icon" type="image/png" sizes="192x192" href="<%= asset_path 'favicon/android-chrome-192x192.png' %>">

<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">

<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-150x150.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">

<meta name="theme-color" content="#ffffff">

app/views/layouts/_flash_message.html.slim
- flash.now[message_type.to_sym] = message unless message.blank?
= flash_messages_helper

app/views/layouts/_footer.html.slim
- if current_page?(root_path)
  br
  .jumbotron.as-seen-on.mb-0.pt-4
    .row
      .col
        h4.text-center
          | As seen on
    .row
      .container
        hr
    .row.justify-content-center
      .col-10
        = image_tag("as-seen-on.png", class: "img-fluid")
- else
  br
footer.footer.bg-dark.text-white
  .container
    br
    / nav.nav.nav-pills.float-right
      = link_to "<i class='fa fa-arrow-circle-up'></i>&nbsp;Back to top".html_safe, root_path, class: "nav-link"
    nav#footer-nav.nav.nav-pills.justify-content-between
      = link_to "About", about_path, class: "nav-link"
      = link_to "Pricing", new_membership_path, class: "nav-link"
      = link_to "Contact", new_contact_form_path, class: "nav-link"
      / = link_to "Blog", blog_path, class: "nav-link"
      = link_to "FAQ", faq_path, class: "nav-link"
      = link_to "Terms of service", terms_path, class: "nav-link"
      = link_to "Privacy policy", privacy_path, class: "nav-link"
      = link_to "DMCA compliance", dmca_path, class: "nav-link"
    br
    p.text-center
      | Copyright 2019 &copy; GetAudioFromVideo.com

app/views/layouts/_modals.html.slim
div class="modal fade" id="loginModalCenter" tabindex="-1" role="dialog" aria-labelledby="loginModalCenterTitle" aria-hidden="true"
  div class="modal-dialog" role="document"
    div class="modal-content"
      div class="modal-header"
        h5 class="modal-title" id="loginModalLongTitle" Login
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      div class="modal-body"
        / - title 'Login'
        .row.justify-content-center
          .col-sm-6.col-md-8
            = link_to "<span class='fa fa-facebook'></span> Facebook login".html_safe, member_facebook_omniauth_authorize_path, method: :post, class: "btn btn-block btn-social btn-facebook"
            = link_to "<span class='fa fa-google'></span> Google login".html_safe, member_google_oauth2_omniauth_authorize_path, method: :post, class: "btn btn-block btn-social btn-google"
        .row.justify-content-between.my-2
          .col
            hr
          .col-2.text-center
            | or
          .col
            hr
        = form_for(resource, as: resource_name, url: session_path(resource_name), html: {id: 'modal_signin_member'}) do |f|
          .form-group
            .float-right
              / | Don't have an account?
              button type="button" class="modal-btn cursor-pointer" data-toggle="modal" data-target="#signupModalCenter" Need to create an account?
            = f.label :email
            = f.email_field :email, autofocus: true, class: "form-control", required: true
          .form-group
            = f.label :password
            = f.password_field :password, autocomplete: "off", class: "form-control", required: true
          = recaptcha_tags
          - if devise_mapping.rememberable?
            .form-group
              - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
                button type="button" class="modal-btn float-right float-link cursor-pointer" data-toggle="modal" data-target="#forgotPasswordModal" Forgot password?
              .form-check
                = f.check_box :remember_me, class: "form-check-input"
                = f.label :remember_me, class: "form-check-label"
          .actions
            = f.submit "Login", class: "btn btn-block btn-success"
            = render "devise/shared/links", login_modal: true
          br

div class="modal fade" id="signupModalCenter" tabindex="-1" role="dialog" aria-labelledby="signupModalCenterTitle" aria-hidden="true"
  div class="modal-dialog" role="document"
    div class="modal-content"
      div class="modal-header"
        - modalTitle = ( (request.url.match('/videos') || request.url.match('/videos/download')) && request.url.exclude?('/videos/search?terms=') ) ? 'Account required, please signup' : 'Create a new account'
        h5 class="modal-title" id="signupModalLongTitle" = modalTitle
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      div class="modal-body"
        / - title 'Signup'
        - if ( (request.url.match('/videos') || request.url.match('/videos/download')) && request.url.exclude?('/videos/search?terms='))
          .row
            .col
              .alert.alert-danger role="alert"
                |  Create a FREE account or login to download your video.
        - elsif request.url.match('/membership/new')
          .row
            .col
              .alert.alert-danger role="alert"
                | Please create an account or login first.
        .row.justify-content-center
          .col-sm-6.col-md-8
            = link_to "<span class='fa fa-facebook'></span> Facebook signup".html_safe, member_facebook_omniauth_authorize_path, method: :post, class: "btn btn-block btn-social btn-facebook"
            = link_to "<span class='fa fa-google'></span> Google signup".html_safe, member_google_oauth2_omniauth_authorize_path, method: :post, class: "btn btn-block btn-social btn-google"
        .row.justify-content-between.my-2
          .col
            hr
          .col-2.text-center
            | or
          .col
            hr
        = form_for(resource, as: resource_name, url: registration_path(resource_name), html: {id: 'modal_signup_member'}) do |f|
          .form-group
            = f.label :email
            = f.email_field :email, autofocus: true, class: "form-control", required: true
          .form-group
            = f.label :password
            - if @minimum_password_length
              small
                i.text-muted
                  |  (
                  = @minimum_password_length
                  |  characters minimum)
            = f.password_field :password, autocomplete: "off", class: "form-control", required: true
          .form-group
            = f.label :password_confirmation
            = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", required: true
          = recaptcha_tags
          .actions
            = f.submit "Sign up", class: "btn btn-block btn-success"
            = render "devise/shared/links", login_modal: false
          br

div class="modal fade" id="forgotPasswordModal" tabindex="-1" role="dialog" aria-labelledby="forgotPasswordModalTitle" aria-hidden="true"
  div class="modal-dialog" role="document"
    div class="modal-content"
      div class="modal-header"
        h5 class="modal-title" id="forgotPasswordModalLongTitle" Forgot your password?
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      div class="modal-body"
        = form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, id: 'modal_forgot_password'}) do |f|
          = devise_error_messages_helper!
          .form-group
            = f.label :email
            = f.email_field :email, autofocus: true, class: "form-control", required: true
          .actions
            = f.submit "Send me reset password instructions", class: "btn btn-block btn-success"
            / = render "devise/shared/links"
            / = render "devise/shared/cancel_button"
            br

div class="modal fade" id="resendConfirmModal" tabindex="-1" role="dialog" aria-labelledby="resendConfirmModalTitle" aria-hidden="true"
  div class="modal-dialog" role="document"
    div class="modal-content"
      div class="modal-header"
        h5 class="modal-title" id="resendConfirmModalLongTitle" Didn't receive confirmation email?
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      div class="modal-body"
        = form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post, id: 'modal_resend_confirmation'}) do |f|
          = devise_error_messages_helper!
          .form-group
            = f.label :email
            = f.email_field :email, autofocus: true, value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email), class: "form-control", required: true
          .actions
            = f.submit "Resend confirmation email", class: "btn btn-block btn-success"
            / = render "devise/shared/links"
            / = render "devise/shared/cancel_button"
            br

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top.justify-content-between
  a.navbar-brand[href=(root_path)]
    strong
      .d-none.d-sm-inline
        | GetAudioFromVideo.com
      .d-inline.d-sm-none
        | GAFV
  - unless current_page?(root_path)
    span#navbar-search.mx-auto
      = form_tag(videos_search_path, method: "get", enforce_utf8: false, class: "form-inline") do
        .input-group
          = text_field_tag :terms, params[:terms], placeholder: "Enter search terms", class: "navbar-search-width-12 border-1px form-control", required: true
          .input-group-btn.input-group-append
            / button.btn.btn-secondary.dropdown-toggle.border-right-0 aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" class="cursor-pointer"
            button.btn.btn-secondary.border-right-0.cursor-default
              | Youtube
            / .dropdown-menu.dropdown-menu-right.disabled
              / a.dropdown-item Vimeo
              / a.dropdown-item Dailymotion
          .input-group-btn.input-group-append
            = submit_tag "Search", :name => nil, class: "btn btn-primary"
  button.navbar-toggler.cursor-pointer[type="button" data-toggle="collapse" data-target="#navbar-gafv" aria-controls="navbar-gafv" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbar-gafv.collapse.navbar-collapse.flew-grow-quarter-default
    ul.navbar-nav.ml-auto
      - unless current_member
        li.nav-item
          button type="button" class="nav-link modal-btn cursor-pointer" data-toggle="modal" data-target="#loginModalCenter" Login
          = render partial: 'layouts/modals.html.slim'
        li.nav-item
          = link_to "Create Account".html_safe, new_membership_path, class: "btn btn-outline-danger"
      - else
        / = navbar_member_badge_helper(current_member)
        - if current_member.subscriptions.active.any?
          li.nav-item
            = link_to "<i class='fa fa-user-circle'></i> Member".html_safe, subscriptions_path, class: "btn btn-success"
        - else
          li.nav-item
            = link_to "<i class='fa fa-exclamation-triangle'></i> Guest".html_safe, new_membership_path, class: "btn btn-danger"
        li.nav-item.dropdown
          a#dropdown-myaccount.nav-link.dropdown-toggle[href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
            = image_tag member_image_helper(current_member), size: 20, class: "rounded-circle"
            | &nbsp;&nbsp;
            = current_member.email
          .dropdown-menu.dropdown-menu-right[aria-labelledby="dropdown-myaccount"]
            / a.dropdown-item[href="#"]
            = link_to "<i class='fa fa-user'></i> Profile".html_safe, edit_member_registration_path, class: "dropdown-item"
            = link_to "<i class='fa fa-usd'></i> Membership".html_safe, subscriptions_path, class: "dropdown-item"
            = link_to "<i class='fa fa-download'></i> Download history".html_safe, download_history_path, class: "dropdown-item"
            .dropdown-divider
            = link_to "<i class='fa fa-sign-out'></i> Logout".html_safe, "javascript:void(0)",
              class: "dropdown-item sweet-alert", method: :delete, data: {message: "Are you sure you want to logout?", link: "/logout"}

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]

    meta[name="description" content="#{yield_meta_tag(:description, 'Get audio from video easily with our Youtube converter tool. Convert Youtube to MP3 to get audio from Youtube in seconds.')}"]
    meta[name="keywords" content="#{yield_meta_tag(:keywords, 'get audio from video, get audio from youtube, convert youtube to mp3, youtube converter')}"]
    meta[name="author" content=""]

    = csrf_meta_tags
    = action_cable_meta_tag

    - if content_for?(:title)
      title
        = yield(:title) + ' | GetAudioFromVideo.com'
    - else
      title GetAudioFromVideo.com

    = Gon::Base.render_data
    = render 'layouts/favicon'

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    / source: https://github.com/turbolinks/turbolinks#working-with-script-elements
    = javascript_include_tag "//platform-api.sharethis.com/js/sharethis.js#property=5c515ab9d72949001bcca394&product=sticky-share-buttons", "data-turbolinks-eval": "false"
    - if Rails.env.production?
      = javascript_include_tag "https://www.googletagmanager.com/gtag/js?id=UA-8374148-1", async: true

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    / WARNING: Respond.js doesn't work if you view the page via file:// -->
    / [if lt IE 9]>
    /   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    /   <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    / <![endif]

  body
    = render "layouts/navbar"

    - access_denied_message_helper()

    .container-fluid
      .row.justify-content-end
        = flash_messages_helper

    = yield

    = render "layouts/footer"

    / back-to-top button
    / a.cd-top[href="#0"]

app/views/layouts/exception.html.slim
doctype html
html
  /! Head
  head
    = content_tag :title, "Error - #{@exception.status} (#{@exception.response.to_s.gsub("_", " ").titleize}) | GetAudioFromVideo.com"

    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    meta[name="description" content="#{yield_meta_tag(:description, 'Get audio from video with our online Youtube converter')}"]
    meta[name="keywords" content="#{yield_meta_tag(:keywords, 'get audio from video, get audio from youtube, convert youtube videos, youtube converter')}"]
    meta[name="author" content=""]

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    = csrf_meta_tags
    = action_cable_meta_tag

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    / WARNING: Respond.js doesn't work if you view the page via file:// -->
    / [if lt IE 9]>
    /   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    /   <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    / <![endif]
  body
    = render "layouts/navbar"

    .container
      .row.justify-content-center
        .col-10
          .jumbotron.text-center
            = content_tag :div, class: "exception", data: { status: @exception.status, response: @exception.response.to_s.humanize, rails: Rails.version }, onclick: ("location.href=\"#{root_url}\";" if @exception.status == "500" && Rails.application.routes.recognize_path("/")), title: ("Return Home" if @exception.status == "500" && Rails.application.routes.recognize_path("/")) do
              / = content_tag :span, @exception.description.html_safe
              = content_tag :h3, "Error: #{@exception.status} (#{@exception.response.to_s.gsub("_", " ").titleize})"
      .row.justify-content-center
        .col-10.text-center
          h6 Oops something went wrong, we have been automatically notified of this problem.

    = render "layouts/footer"

    / back-to-top button
    a.cd-top[href="#0"]